baseURL = "https://mrdonbrown.com/"
disableKinds = ['taxonomy', 'term']

[taxonomies]
    category = 'categories'




[caches]
    [caches.images]
        dir    = ':cacheDir/galleriesdeluxe'
        maxAge = "4320h"                     # 6 months.

[params]
    [params.author]
        name        = "Don Brown"
        email       = "donald.brown@gmail.com"
        description = "Pictures"

    [params.galleriesdeluxe]
        # One of dartsass or libsass.
        sass_transpiler = "libsass"
        [params.galleriesdeluxe.sassvars]
            color_background = "#1d1e2c"

[params.gallerydeluxe]
    shuffle     = false
    reverse     = false
    enable_exif = false

[imaging]
    resampleFilter = "CatmullRom"
    quality        = 71
    anchor         = "smart"
    [imaging.exif]
        disableDate    = false
        disableLatLong = true
        includeFields  = 'Artist|LensModel|FNumber|ExposureTime'

[module]
    [[module.mounts]]
        source = "assets"
        target = "assets"
    [[module.mounts]]
        source = "content"
        target = "content"
    [[module.mounts]]
        source = "layouts"
        target = "layouts"

    [[module.imports]]
        path = "github.com/bep/galleriesdeluxe"